### ISSUE TITLE
Hydra Provider HeartBeat 

### ISSUE THREAD

**Issue by NoahSprenger** [uorocketry/rgs#105]
We want some way to know if the service is alive. What does a healthy service look like? Radio is plugged into USB, dropped messages rate, etc. This endpoint should return 200 if all is good and (pick the appropriate one from the list https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

**Comment by seofernando25** [comment]
As of #110  Hydra Provider is now using a GRPC server.
It has a Health Service that always returns "SERVING" (aka healthy)

We could have a dedicated "SerialComm" service so that when we probe the health service for the serial comm service health we could get its SERVING status.

In regards to a more detailed metrics it could be included as a GRPC function

**Comment by seofernando25** [comment]
Intersects with #111
